CREATE TABLE "agents" (
	"id" text PRIMARY KEY DEFAULT 'agt_' || gen_random_uuid(),
	"public_key" text UNIQUE,
	"display_name" text NOT NULL,
	"version" text NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"metadata" jsonb,
	"expires_at" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "audit_events" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "audit_events_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"trace_id" text NOT NULL,
	"seq_no" integer NOT NULL,
	"timestamp" timestamp DEFAULT now() NOT NULL,
	"actor_type" text NOT NULL,
	"actor_id" text NOT NULL,
	"event_type" text NOT NULL,
	"intent_mandate_id" text,
	"cart_mandate_id" text,
	"decision_id" text,
	"payment_action_id" text,
	"reason_codes" jsonb,
	"provider_refs" jsonb,
	"snapshot_hash" text,
	"explanation" text NOT NULL,
	"metadata" jsonb DEFAULT '{}' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "budget_reservations" (
	"id" text PRIMARY KEY DEFAULT 'bres_' || gen_random_uuid(),
	"intent_mandate_id" text NOT NULL,
	"amount_minor" integer NOT NULL,
	"status" text DEFAULT 'reserved' NOT NULL,
	"expires_at" timestamp NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "cart_mandates" (
	"id" text PRIMARY KEY DEFAULT 'cart_' || gen_random_uuid(),
	"intent_mandate_id" text NOT NULL,
	"merchant_id" text NOT NULL,
	"quote_expires_at" timestamp NOT NULL,
	"total_minor" integer NOT NULL,
	"currency" text DEFAULT 'INR' NOT NULL,
	"items" jsonb NOT NULL,
	"fulfillment" jsonb NOT NULL,
	"terms" jsonb NOT NULL,
	"content_hash" text NOT NULL,
	"status" text DEFAULT 'proposed' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "intent_mandates" (
	"id" text PRIMARY KEY DEFAULT 'int_' || gen_random_uuid(),
	"user_id" text NOT NULL,
	"agent_id" text NOT NULL,
	"mandate_json" jsonb NOT NULL,
	"max_transaction_minor" integer NOT NULL,
	"currency" text DEFAULT 'INR' NOT NULL,
	"validity_expires_at" timestamp NOT NULL,
	"status" text DEFAULT 'active' NOT NULL,
	"approved_at" timestamp DEFAULT now() NOT NULL,
	"revoked_at" timestamp
);
--> statement-breakpoint
CREATE TABLE "merchants" (
	"id" text PRIMARY KEY DEFAULT 'mch_' || gen_random_uuid(),
	"name" text NOT NULL,
	"api_key_hash" text NOT NULL,
	"webhook_secret" text NOT NULL,
	"status" text DEFAULT 'active' NOT NULL,
	"config" jsonb DEFAULT '{}' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "payment_actions" (
	"id" text PRIMARY KEY DEFAULT 'pact_' || gen_random_uuid(),
	"cart_mandate_id" text NOT NULL UNIQUE,
	"decision_id" text NOT NULL UNIQUE,
	"budget_reservation_id" text NOT NULL UNIQUE,
	"amount_minor" integer NOT NULL,
	"currency" text DEFAULT 'INR' NOT NULL,
	"status" text DEFAULT 'pending_approval' NOT NULL,
	"razorpay_order_id" text UNIQUE,
	"razorpay_payment_id" text UNIQUE,
	"provider_metadata" jsonb,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "policy_decisions" (
	"id" text PRIMARY KEY DEFAULT 'dec_' || gen_random_uuid(),
	"intent_mandate_id" text NOT NULL,
	"cart_mandate_id" text NOT NULL CONSTRAINT "idx_policy_active_unique" UNIQUE,
	"decision" text NOT NULL,
	"reason_codes" jsonb NOT NULL,
	"decision_json" jsonb NOT NULL,
	"expires_at" timestamp NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "products" (
	"id" text PRIMARY KEY DEFAULT 'prod_' || gen_random_uuid(),
	"merchant_id" text NOT NULL,
	"variant_id" text NOT NULL UNIQUE,
	"title" text NOT NULL,
	"description" text,
	"category" text NOT NULL,
	"attributes" jsonb DEFAULT '{}' NOT NULL,
	"base_price_minor" integer NOT NULL,
	"currency" text DEFAULT 'INR' NOT NULL,
	"tax_rate_bps" integer DEFAULT 1800 NOT NULL,
	"returnable" boolean DEFAULT true NOT NULL,
	"return_window_days" integer DEFAULT 7,
	"stock_quantity" integer DEFAULT 0 NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "refund_actions" (
	"id" text PRIMARY KEY DEFAULT 'ref_' || gen_random_uuid(),
	"payment_action_id" text NOT NULL,
	"amount_minor" integer NOT NULL,
	"razorpay_refund_id" text UNIQUE,
	"status" text DEFAULT 'pending' NOT NULL,
	"idempotency_key" text NOT NULL UNIQUE,
	"reason" text,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "webhook_events" (
	"id" text PRIMARY KEY DEFAULT 'we_' || gen_random_uuid(),
	"provider_event_id" text NOT NULL UNIQUE,
	"provider" text DEFAULT 'razorpay' NOT NULL,
	"raw_payload" jsonb NOT NULL,
	"status" text DEFAULT 'processed' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE INDEX "idx_agents_status" ON "agents" ("status");--> statement-breakpoint
CREATE INDEX "idx_audit_trace" ON "audit_events" ("trace_id","seq_no");--> statement-breakpoint
CREATE INDEX "idx_budget_intent" ON "budget_reservations" ("intent_mandate_id") WHERE status = 'reserved';--> statement-breakpoint
CREATE INDEX "idx_cart_intent" ON "cart_mandates" ("intent_mandate_id");--> statement-breakpoint
CREATE INDEX "idx_cart_merchant" ON "cart_mandates" ("merchant_id");--> statement-breakpoint
CREATE INDEX "idx_cart_expiry" ON "cart_mandates" ("quote_expires_at") WHERE status = 'proposed';--> statement-breakpoint
CREATE INDEX "idx_intent_agent" ON "intent_mandates" ("agent_id");--> statement-breakpoint
CREATE INDEX "idx_intent_user" ON "intent_mandates" ("user_id");--> statement-breakpoint
CREATE INDEX "idx_intent_expiry" ON "intent_mandates" ("validity_expires_at") WHERE status = 'active';--> statement-breakpoint
CREATE INDEX "idx_payment_order" ON "payment_actions" ("razorpay_order_id") WHERE razorpay_order_id IS NOT NULL;--> statement-breakpoint
CREATE INDEX "idx_policy_cart" ON "policy_decisions" ("cart_mandate_id");--> statement-breakpoint
CREATE INDEX "idx_policy_intent" ON "policy_decisions" ("intent_mandate_id");--> statement-breakpoint
CREATE INDEX "idx_products_merchant" ON "products" ("merchant_id");--> statement-breakpoint
CREATE INDEX "idx_products_category" ON "products" ("category");--> statement-breakpoint
CREATE INDEX "idx_webhook_provider" ON "webhook_events" ("provider_event_id");--> statement-breakpoint
ALTER TABLE "budget_reservations" ADD CONSTRAINT "budget_reservations_intent_mandate_id_intent_mandates_id_fkey" FOREIGN KEY ("intent_mandate_id") REFERENCES "intent_mandates"("id");--> statement-breakpoint
ALTER TABLE "cart_mandates" ADD CONSTRAINT "cart_mandates_intent_mandate_id_intent_mandates_id_fkey" FOREIGN KEY ("intent_mandate_id") REFERENCES "intent_mandates"("id");--> statement-breakpoint
ALTER TABLE "cart_mandates" ADD CONSTRAINT "cart_mandates_merchant_id_merchants_id_fkey" FOREIGN KEY ("merchant_id") REFERENCES "merchants"("id");--> statement-breakpoint
ALTER TABLE "intent_mandates" ADD CONSTRAINT "intent_mandates_agent_id_agents_id_fkey" FOREIGN KEY ("agent_id") REFERENCES "agents"("id");--> statement-breakpoint
ALTER TABLE "payment_actions" ADD CONSTRAINT "payment_actions_cart_mandate_id_cart_mandates_id_fkey" FOREIGN KEY ("cart_mandate_id") REFERENCES "cart_mandates"("id");--> statement-breakpoint
ALTER TABLE "payment_actions" ADD CONSTRAINT "payment_actions_decision_id_policy_decisions_id_fkey" FOREIGN KEY ("decision_id") REFERENCES "policy_decisions"("id");--> statement-breakpoint
ALTER TABLE "payment_actions" ADD CONSTRAINT "payment_actions_3dHOIbe97Frv_fkey" FOREIGN KEY ("budget_reservation_id") REFERENCES "budget_reservations"("id");--> statement-breakpoint
ALTER TABLE "policy_decisions" ADD CONSTRAINT "policy_decisions_intent_mandate_id_intent_mandates_id_fkey" FOREIGN KEY ("intent_mandate_id") REFERENCES "intent_mandates"("id");--> statement-breakpoint
ALTER TABLE "policy_decisions" ADD CONSTRAINT "policy_decisions_cart_mandate_id_cart_mandates_id_fkey" FOREIGN KEY ("cart_mandate_id") REFERENCES "cart_mandates"("id");--> statement-breakpoint
ALTER TABLE "products" ADD CONSTRAINT "products_merchant_id_merchants_id_fkey" FOREIGN KEY ("merchant_id") REFERENCES "merchants"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "refund_actions" ADD CONSTRAINT "refund_actions_payment_action_id_payment_actions_id_fkey" FOREIGN KEY ("payment_action_id") REFERENCES "payment_actions"("id");